--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: BonusQuestion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."BonusQuestion" (
    id smallint NOT NULL,
    question jsonb NOT NULL,
    question_type smallint NOT NULL,
    answer character(64) NOT NULL,
    lifeline_id smallint NOT NULL,
    available_from timestamp with time zone NOT NULL,
    available_to timestamp with time zone NOT NULL
);


ALTER TABLE public."BonusQuestion" OWNER TO postgres;

--
-- Name: Bonues_question_id_sec; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."BonusQuestion" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Bonues_question_id_sec"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Hint; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Hint" (
    id smallint NOT NULL,
    number smallint NOT NULL,
    question_number smallint NOT NULL,
    hint text NOT NULL,
    is_released boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Hint" OWNER TO postgres;

--
-- Name: Hint_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Hint" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Hint_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Lifeline; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Lifeline" (
    id smallint NOT NULL,
    lifeline character varying(255) NOT NULL,
    initial_question smallint NOT NULL,
    final_question smallint NOT NULL
);


ALTER TABLE public."Lifeline" OWNER TO postgres;

--
-- Name: Lifeline_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Lifeline" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Lifeline_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Question" (
    id smallint NOT NULL,
    question_number smallint NOT NULL,
    question jsonb NOT NULL,
    question_type smallint NOT NULL,
    answer character(64) NOT NULL
);


ALTER TABLE public."Question" OWNER TO postgres;

--
-- Name: Question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Question" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Question_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    email_id character varying(255) NOT NULL,
    username character varying(31) NOT NULL,
    id integer NOT NULL,
    lifelines text[] DEFAULT '{}'::text[] NOT NULL,
    question_number integer DEFAULT 0 NOT NULL,
    last_modified timestamp with time zone DEFAULT now() NOT NULL,
    bonus_questions integer[] DEFAULT '{}'::integer[] NOT NULL
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- Name: User_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: BonusQuestion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."BonusQuestion" (id, question, question_type, answer, lifeline_id, available_from, available_to) FROM stdin;
1	{"url": "https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"}	1	936a185caaa266bb9cbe981e9e05cb78cd732b0b3280eb944412bb6f8f8f07af	1	2021-03-03 17:00:00+05:30	2021-03-04 14:00:00+05:30
2	{"url": "https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"}	1	936a185caaa266bb9cbe981e9e05cb78cd732b0b3280eb944412bb6f8f8f07af	2	2021-03-03 19:00:00+05:30	2021-03-04 14:00:00+05:30
\.


--
-- Data for Name: Hint; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Hint" (id, number, question_number, hint, is_released) FROM stdin;
14	4	1	41	f
11	1	1	11	t
12	2	1	21	t
13	3	1	31	t
15	1	2	12	t
16	2	2	22	t
17	3	2	32	t
18	4	2	42	f
19	1	3	13	t
20	2	3	23	t
21	3	3	33	f
22	1	4	14	t
24	2	4	24	t
25	3	4	24	f
26	1	5	15	t
27	2	5	25	t
28	3	5	35	f
\.


--
-- Data for Name: Lifeline; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Lifeline" (id, lifeline, initial_question, final_question) FROM stdin;
1	Skip Question	1	3
2	Get Hint	2	5
\.


--
-- Data for Name: Question; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Question" (id, question_number, question, question_type, answer) FROM stdin;
12	0	{"url": "https://res.cloudinary.com/do3uy82tk/image/upload/v1614770439/Skyvory.png"}	1	936a185caaa266bb9cbe981e9e05cb78cd732b0b3280eb944412bb6f8f8f07af
13	1	{"url": "https://res.cloudinary.com/do3uy82tk/image/upload/v1614770439/Itschessbabbbyyyy.png"}	1	936a185caaa266bb9cbe981e9e05cb78cd732b0b3280eb944412bb6f8f8f07af
14	2	{"url": "https://res.cloudinary.com/do3uy82tk/image/upload/v1614770436/Criminallondon.png"}	1	936a185caaa266bb9cbe981e9e05cb78cd732b0b3280eb944412bb6f8f8f07af
15	3	{"url": "https://res.cloudinary.com/do3uy82tk/image/upload/v1614770436/RGlayBCcm9kaWU.jpg"}	1	936a185caaa266bb9cbe981e9e05cb78cd732b0b3280eb944412bb6f8f8f07af
16	4	{"url": "https://res.cloudinary.com/do3uy82tk/image/upload/v1614770436/Maybe.png"}	1	936a185caaa266bb9cbe981e9e05cb78cd732b0b3280eb944412bb6f8f8f07af
17	5	{"url": "https://res.cloudinary.com/do3uy82tk/image/upload/v1614770436/Matricesanddeterminants.png"}	1	936a185caaa266bb9cbe981e9e05cb78cd732b0b3280eb944412bb6f8f8f07af
\.


--
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User" (email_id, username, id, lifelines, question_number, last_modified, bonus_questions) FROM stdin;
\.


--
-- Name: Bonues_question_id_sec; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Bonues_question_id_sec"', 2, true);


--
-- Name: Hint_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Hint_id_seq"', 29, true);


--
-- Name: Lifeline_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Lifeline_id_seq"', 2, true);


--
-- Name: Question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Question_id_seq"', 17, true);


--
-- Name: User_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_id_seq"', 35, true);


--
-- Name: BonusQuestion BonusQuestion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BonusQuestion"
    ADD CONSTRAINT "BonusQuestion_pkey" PRIMARY KEY (id);


--
-- Name: Lifeline Lifeline_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lifeline"
    ADD CONSTRAINT "Lifeline_pkey" PRIMARY KEY (id);


--
-- Name: User email_id_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT email_id_unique UNIQUE (email_id);


--
-- Name: Hint hint_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Hint"
    ADD CONSTRAINT hint_pk PRIMARY KEY (id);


--
-- Name: Question question_number_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Question"
    ADD CONSTRAINT question_number_unique UNIQUE (question_number);


--
-- Name: Question question_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Question"
    ADD CONSTRAINT question_pk PRIMARY KEY (id);


--
-- Name: User user_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT user_pk PRIMARY KEY (id);


--
-- Name: User username_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT username_unique UNIQUE (username);


--
-- Name: user_id_uindex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX user_id_uindex ON public."User" USING btree (id);


--
-- Name: BonusQuestion lifeline_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."BonusQuestion"
    ADD CONSTRAINT lifeline_id_fk FOREIGN KEY (lifeline_id) REFERENCES public."Lifeline"(id);


--
-- PostgreSQL database dump complete
--

